name: Ballerina Daily Test

on:
  schedule:
    - cron: '30 19 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ballerina
      uses: ballerina-platform/setup-ballerina@v1

    - name: Run tests
      run: bal test
