name: Ballerina Daily Test

on:
  schedule:
    - cron: '10 7 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ballerina
      uses: ballerina-platform/ballerina-action@v1

    - name: Run tests
      run: bal test
